-- three columns, separated by at least one tab:
-- grammar, testdata, expected result

TEST <- 'a'			a		OK
TEST <- 'a'			aa		OK
TEST <- 'a'			-		NOK
TEST <- 'a'^foo			a		ERR_COMP
TEST <- 'a'^2-1			a		ERR_COMP
TEST <- 'a'^1-1			a		OK
TEST <- 'a'^1-1			-		NOK
TEST <- 'a'?			a		OK
TEST <- 'a'?			-		OK
TEST <- 'a'^-1			a		OK
TEST <- 'a'^-1			-		OK
TEST <- 'a'^0-1			a		OK
TEST <- 'a'^0-1			-		OK
TEST <- 'a'*			-		OK
TEST <- 'a'*			a		OK
TEST <- 'a'*			aa		OK
TEST <- 'a'^0-			a		OK
TEST <- 'a'^0-			aa		OK
TEST <- 'a'+			-		NOK
TEST <- 'a'+			a		OK
TEST <- 'a'+			aa		OK
TEST <- 'a'^-2			-		OK
TEST <- 'a'^-2			a		OK
TEST <- 'a'^-2			aa		OK
TEST <- 'a'^-2			aaa		OK
TEST <- 'a'^-8			aaaaaa		OK
TEST <- 'a'^-8			aaaaaaaaaa	OK
TEST <- 'a'^1-			-		NOK
TEST <- 'a'^1-			a		OK
TEST <- 'a'^1-			aaa		OK
TEST <- 'a'^1-2			-		NOK
TEST <- 'a'^1-2			a		OK
TEST <- 'a'^1-2			aa		OK
TEST <- 'a'^1-2			aba		OK
TEST <- 'a'^1-2			baa		NOK
TEST <- 'a'^1-2			aaa		OK
TEST <- 'a'^1-3			-		NOK
TEST <- 'a'^1-3			a		OK
TEST <- 'a'^1-3			aa		OK
TEST <- 'a'^1-3			aaa		OK
TEST <- 'a'^1-3			aaaa		OK
TEST <- 'a'^1-8			-		NOK
TEST <- 'a'^1-8			aa		OK
TEST <- 'a'^3			-		NOK
TEST <- 'a'^3			a		NOK
TEST <- 'a'^3			aa		NOK
TEST <- 'a'^3			aaa		OK
TEST <- 'a'^3			aaaa		OK
TEST <- 'a'^3-3			aa		NOK
TEST <- 'a'^3-3			aaa		OK
TEST <- 'a'^3-4			aa		NOK
TEST <- 'a'^3-4			aaa		OK
TEST <- 'a'^3-4			aaaa		OK
TEST <- 'a'^3-4			aaaaa		OK
TEST <- 'a'^3-5			aa		NOK
TEST <- 'a'^3-5			aaa		OK
TEST <- 'a'^3-5			aaaa		OK
TEST <- 'a'^3-5			aaaaa		OK
TEST <- 'a'^3-5			aaaaaa		OK
