#!/usr/bin/perl

use strict;

my $inputfile = '-';
my $input = '';

my $outputfile = '-';
my $output = '';

while (scalar(@ARGV)) {
  my $arg = shift @ARGV;
  if ($arg =~ s/^-//) {
    if ($arg eq 'i') {
      $inputfile = shift @ARGV || die "No input file specified.";
    } elsif ($arg eq 'o') {
      $outputfile = shift @ARGV || die "No output file specified.";
    } else {
      die "Unrecognized option -$arg.";
    }
  }
}

if ($inputfile eq '-') {
  $input = join('', <STDIN>);
} else {
  $input = absorb_binary($inputfile);
}

my @jumpinstr = (
  undef, undef, undef, 'call', undef, 'catch', 'commit', 'backcommit', 'partialcommit'
);
disassemble();

if ($outputfile eq '-') {
  print $output;
}

exit 0;

##---- functions ----##

sub disassemble
{
  my $label = 0;
  while (length($input)) {
    $input =~ s/^(.)(.)(.)(.)//s;
    my @bytes = ( ord($1), ord($2), ord($3), ord($4) );
    my $opcode = $bytes[ 0 ] >> 4;
    $output .= ($label * 4) . ": ";
    if ($opcode == 1) {
      $output .= "end " . (
        ($bytes[1] << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
    } elsif ($opcode == 2) {
      $output .=
        "range " . sprintf("%.2x", $bytes[2]) .
        " " . sprintf("%.2x", $bytes[3]);
      if ($bytes[1] != 0xff) {
        $output .= ' ' . sprintf("%.2x", $bytes[1]);
      }
    } elsif ($opcode == 3 ||
             $opcode == 5 ||
             $opcode == 6 ||
             $opcode == 7 ||
             $opcode == 8)
    {
      $output .= $jumpinstr[$opcode] . ' '. (
        ($bytes[1] << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
    } elsif ($opcode == 4) {
      $output .= "ret";
    } elsif ($opcode == 9) {
      $output .= "fail";
    } elsif ($opcode == 10) {
      $output .= "failtwice";
    } elsif ($opcode == 11) {
      $output .= "var ";
    } elsif ($opcode == 12) {
      $output .= "opencapture ";
    } elsif ($opcode == 13) {
      $output .= "closecapture ";
    } elsif ($opcode == 14) {
      $output .= "counter ";
    } elsif ($opcode == 15) {
      $output .= "condjump ";
    } else {
      die "Unknown opcode $opcode.";
    }
    $output .= "\n";
    ++$label;
  }
}

sub absorb_binary
{
  my $path = shift; die "$path not found" if (! -f $path);
  my $result = '';
  die "Error $@ opening $path" if (!open(FILE, '<', $path));
  binmode FILE;
  my $buf;
  while (1) {
    my $n = sysread(FILE, $buf, 1024);
    if (!$n) {
      close FILE;
      return $result;
    }
    $result .= $buf;
  }
}

1;
