#!/usr/bin/perl

use strict;

my $inputfile = '-';
my $input = '';

my $outputfile = '-';

my %labeltokens = (
  'call', 0x30,
  'catch', 0x50,
  'commit', 0x60,
  'backcommit', 0x70,
  'partialcommit', 0x80,
);

my %regtokens = (
  'var', 0xb0,
  'opencapture', 0xc0,
  'closecapture', 0xd0,
);

while (scalar(@ARGV)) {
  my $arg = shift @ARGV;
  if ($arg =~ s/^-//) {
    if ($arg eq 'i') {
      $inputfile = shift @ARGV || die "No input file specified.";
    } elsif ($arg eq 'o') {
      $outputfile = shift @ARGV || die "No output file specified.";
    } else {
      die "Unrecognized option -$arg.";
    }
  }
}

if ($inputfile eq '-') {
  $input = join('', <STDIN>);
} else {
  $input = `cat $inputfile` || die "Could not absorb input file '$inputfile'";
}

my $setlabel = 0;
my @tokens;
my %labels;
my $output;

tokenize();
first_pass();
second_pass();

if ($outputfile eq '-') {
  syswrite(STDOUT, $output);
} else {
  open FILE, "> $outputfile" || die "Could not open '$outputfile' for output.";
  syswrite(FILE, $output);
  close FILE;
}

exit 0;

##---- functions ----##

sub tokenize
{
  while (length($input)) {
    while (1) {
      last if (0 == ($input =~ s/^[ \t\r\n]+//) && 0 == ($input =~ s/^--(.*)?\n//));
    }
    if ($input =~ s/^([a-zA-Z0-9_]+)://) {
      push @tokens, { type => 'label', label => $1 };
    } elsif ($input =~ s/^end(\s+([0-9]+))?//) {
      push @tokens, { type => 'end', code => $2 };
    } elsif ($input =~ s/^char\s+([a-fA-F0-9]{2})//) {
      push @tokens, { type => 'range', from => hex($1), until => hex($1) };
    } elsif ($input =~ s/^(ret|failtwice|fail)//) {
      push @tokens, { type => $1 };
    } elsif ($input =~ s/^any//) {
      push @tokens, { type => 'range', from => 0, until => 255 };
    } elsif ($input =~ s/^range\s+([a-fA-F0-9]{2})//) {
      my $from = hex($1);
      my $until = $from;
      my $bitmask = 0xff;
      if ($input =~ s/^\s+([a-fA-F0-9]{2})//) {
        $until = hex($1);
        if ($input =~ s/^\s+([a-fA-F0-9]{2})//) {
          $bitmask = hex($1);
        }
      }
      push @tokens, { type => 'range', from => $from, until => $until, bitmask => $bitmask };
    } elsif ($input =~ s/^bitmask\s+([a-fA-F0-9]{2})\s+([a-fA-F0-9]{2})//) {
      push @tokens, { type => 'range', bitmask => hex($1), from => hex($2), until => hex($2) };
    } elsif ($input =~ s/^(open|close)capture\s+([0-9]+)//) {
      push @tokens, { type => "$1capture", reg => $2 };
    } elsif ($input =~ s/^counter\s+([0-9]+)\s+([0-9]+)//) {
      push @tokens, { type => 'counter', reg => $1, value => $2 };
    } elsif ($input =~ s/^condjump\s+([0-9]+)\s+([a-zA-Z0-9_]+)//) {
      push @tokens, { type => 'condjump', reg => $1, label => $2 };
    } elsif ($input =~ s/^(call|catch|(partial|back|)commit)\s+([a-zA-Z0-9_]+)//) {
      push @tokens, { type => $1, label => $3 };
    } elsif ($input =~ s/^quad\s+([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})//) {
      push @tokens,
        { type => 'range', from => hex($1), until => hex($1) },
        { type => 'range', from => hex($2), until => hex($2) },
        { type => 'range', from => hex($3), until => hex($3) },
        { type => 'range', from => hex($4), until => hex($4) };
    } elsif ($input =~ s/^set\s+([0-9a-fA-F]{64})// ) {
      recompile_set($1);
    } elsif (length($input)) {
      die "Unknown token at '$input'.";
    }
  }
}

sub first_pass
{
  my $bc_offset = 0;
  for (my $i=0; $i < scalar(@tokens); $i++) {
    my $token = $tokens[ $i ];
    if ($token->{type} eq 'label') {
      $labels{$token->{label}} = $bc_offset * 4;
    } else {
      ++$bc_offset;
    }
  }
}

sub second_pass
{
  my $bc_offset = 0;
  for (my $i=0; $i < scalar(@tokens); $i++) {
    my $token = $tokens[ $i ];
    if ($token->{type} eq 'label') {
      --$bc_offset;
    } elsif ($token->{type} eq 'end') {
      my $code = $token->{code} & 0x00ffffff;
      $output .= pack(
        'CCCC',
        0x00,
        (($code >> 16) & 0xff),
        (($code >> 8) & 0xff),
        ($code & 0xff)
      );
    } elsif ($token->{type} eq 'range') {
      my $bitmask = (defined($token->{bitmask}) ? $token->{bitmask} : 0xff);
      $output .= pack(
        'CCCC',
        0x10,
        $bitmask,
        $token->{from} & 0xff,
        $token->{until} & 0xff
      );
    } elsif ($token->{type} =~ /^(call|catch|(back|partial|)commit)$/) {
      my $offset;
      if ($token->{label} eq '__NEXT__') {
        $offset = (($bc_offset + 1) * 4);
      } elsif (!defined($labels{$token->{label}})) {
        die "Could not resolve label $token->{label}.";
      } else {
        $offset = $labels{$token->{label}} & 0x000fffff;
      }
      my $opcode = $labeltokens{$token->{type}} || die "Instruction to opcode";
      $output .= pack(
        'CCCC',
        $opcode,
        (($offset >> 16) & 0xff),
        (($offset >> 8) & 0xff),
        ($offset & 0xff)
      );
    } elsif ($token->{type} eq 'ret') {
      $output .= pack('N', 0x40000000);
    } elsif ($token->{type} eq 'fail') {
      $output .= pack('N', 0x90000000);
    } elsif ($token->{type} eq 'failtwice') {
      $output .= pack('N', 0xa0000000);
    } elsif ($token->{type} eq 'counter') {
      my $reg = $token->{reg} & 0xff;
      my $value = $token->{value} & 0x000fffff;
      $output .= pack(
        'CCCC',
        (0xe0 | ($reg >> 4)),
        ((($reg << 4) & 0xff) | ($value >> 16)),
        (($value >> 8) & 0xff),
        ($value & 0xff)
      );
    } elsif ($token->{type} eq 'condjump') {
      my $reg = $token->{reg} & 0xff;
      my $offset = $labels{$token->{label}} & 0x000fffff;
      $output .= pack(
        'CCCC',
        (0xf0 | ($reg >> 4)),
        ((($reg << 4) & 0xff) | ($offset >> 16)),
        (($offset >> 8) & 0xff),
        ($offset & 0xff)
      );
    } elsif ($token->{type} =~ /^(var|(open|close)capture)$/) {
      my $opcode = $regtokens{$token->{type}} || die "Instruction to opcode";
      my $reg = $token->{reg} & 0x0000ffff;
      $output .= pack(
        'CCCC',
        $opcode,
        0x00,
        ($reg >> 8),
        ($reg & 0xff)
      );
    } else {
      die "Unknown token '$token->{type}'.";
    }
    ++$bc_offset;
  }
}

##
# Sets are complicated beasts; not only are they a
# large asm and bytecode instruction (256 bits); they
# also must be recompiled to possibly a list of
# alternatives of ranges. This function tries not to,
# and shouldn't if you use the regular compiler,
# but MAY upset your label namespace.
##
sub recompile_set
{
  my $hex = shift;
  my @set;
  my @ranges;
  my $on = 0;
  my $from;
  for (my $i=0; $i < 64; $i += 2) {
    push @set, hex(substr($hex, $i, 2));
  }
  for (my $i=0; $i < 256; $i++) {
    my $bit = ($set[ int($i / 8) ] & (1 << ($i % 8)));
    if ($bit && !$on) {
      $from = $i;
      $on = 1;
    } elsif (!$bit && $on) {
      push @ranges, [ $from, $i-1 ];
      $on = 0;
      undef $from;
    }
  }
  if (defined($from)) {
    push @ranges, [ $from, 255 ];
  }
  if (scalar(@ranges) == 0) {
    push @tokens, { type => 'fail' };
  } elsif (scalar(@ranges) == 1) {
    push @tokens, { type => 'range', from => $ranges[0]->[0], until => $ranges[0]->[1] };
  } else {
    my $lab = "SET_" . (++$setlabel) . '_';
    for (my $i=0; $i < scalar(@ranges)-1; $i++) {
      push @tokens,
        { type => 'catch', label => "$lab$i" },
        { type => 'range', from => $ranges[$i]->[0], until => $ranges[$i]->[1] },
        { type => 'commit', label => $lab . scalar(@ranges) },
        { type => 'label', label => "$lab$i" },
      ;
    }
    push @tokens,
      { type => 'range', from => $ranges[-1]->[0], until => $ranges[-1]->[1] },
      { type => 'label', label => $lab . scalar(@ranges) },
    ;
  }
}

1;
