/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _GPEG_PR_FUNCTIONS_FUNCTIONS_H_
#define _GPEG_PR_FUNCTIONS_FUNCTIONS_H_

/* declared in ./gpeg_capturelist.c */
#define gpeg_capturelist_debug gen0_gpeg_capturelist_debug

extern
void gpeg_capturelist_debug
  (gpeg_capturelist_t* list);

/* declared in ./gpeg_capturelist.c */
#define gpeg_capture_debug gen0_gpeg_capture_debug

extern
void gpeg_capture_debug
  (gpeg_capture_t* capture);

/* declared in ./gpeg_capturelist.c */
#define gpeg_capturelist_remove gen0_gpeg_capturelist_remove

extern
void gpeg_capturelist_remove
  (gpeg_capturelist_t* list, unsigned type);

/* declared in ./gpeg_compile.c */
#define gpeg_compile gen0_gpeg_compile

extern
int gpeg_compile
  (char* grammar, gpege_t* engine)
  __attribute__ ((warn_unused_result));

/* declared in ./gpeg_opcode2string.c */
#define gpeg_opcode2string gen0_gpeg_opcode2string

extern
char* gpeg_opcode2string
  (unsigned opcode)
  __attribute__ ((warn_unused_result));

/* declared in ./gpeg_run.c */
#define gpeg_run gen0_gpeg_run

extern
int gpeg_run
  (gpege_t* engine, int* resultcode, gpeg_resobj_t* result)
  __attribute__ ((warn_unused_result));



#endif