#!/usr/bin/perl

use strict;

my $inputfile = '-';
my $input = '';

my $outputfile = '-';
my $output = '';

while (scalar(@ARGV)) {
  my $arg = shift @ARGV;
  if ($arg =~ s/^-//) {
    if ($arg eq 'i') {
      $inputfile = shift @ARGV || die "No input file specified.";
    } elsif ($arg eq 'o') {
      $outputfile = shift @ARGV || die "No output file specified.";
    } else {
      die "Unrecognized option -$arg.";
    }
  }
}

if ($inputfile eq '-') {
  $input = join('', <STDIN>);
} else {
  $input = absorb_binary($inputfile);
}

my @jumpinstr = (
  undef, undef, undef, 'call', undef, 'catch', 'commit', 'backcommit', 'partialcommit'
);
disassemble();

if ($outputfile eq '-') {
  print $output;
}

exit 0;

##---- functions ----##

sub disassemble
{
  my $label = 0;
  while (length($input) >= 4) {
    my @bytes;
    for (my $i=0; $i < 4; $i++) {
      my $byte = substr($input, 0, 1);
      $input = substr($input, 1);
      push @bytes, ord($byte);
    }
    my $opcode = $bytes[ 0 ] >> 4;
    $output .= "L_" . sprintf("%.6d", ($label * 4)) . ": ";
    if ($opcode == 0) {
      $output .= "end " . (
        ($bytes[1] << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
    } elsif ($opcode == 1) {
      $output .= "range " . sprintf("%.2x", $bytes[2]);
      if ($bytes[2] != $bytes[3]) {
        $output .= ' ' . sprintf("%.2x", $bytes[3]);
      }
      if ($bytes[1] != 0xff) {
        $output .= ' ' . sprintf("%.2x", $bytes[1]);
      }
    } elsif ($opcode == 2) {
      $output .= 'limit ';
      ##..
    } elsif ($opcode == 3 ||
             $opcode == 5 ||
             $opcode == 6 ||
             $opcode == 7 ||
             $opcode == 8)
    {
      my $offset = (
        ($bytes[1] << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
      $output .= $jumpinstr[$opcode] . ' L_' . sprintf("%.6d", $offset);
    } elsif ($opcode == 4) {
      $output .= "ret";
    } elsif ($opcode == 9) {
      $output .= "fail";
    } elsif ($opcode == 10) {
      $output .= "failtwice";
    } elsif ($opcode == 11) {
      $output .= "var " . (
        ($bytes[2] << 8) |
        $bytes[3]
      );
    } elsif ($opcode == 12) {
      $output .= "opencapture " . (
        ($bytes[2] << 8) |
        $bytes[3]
      ); 
    } elsif ($opcode == 13) {
      $output .= "closecapture " . (
        ($bytes[2] << 8) |
        $bytes[3]
      ); 
    } elsif ($opcode == 14) {
      $output .= "counter " . (
        (($bytes[0] & 0x0f) << 4) |
        (($bytes[1] & 0xf0) >> 4)
      ) . ' ' . (
        (($bytes[1] & 0x0f) << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
    } elsif ($opcode == 15) {
      my $offset = (
        (($bytes[1] & 0x0f) << 16) |
        ($bytes[2] << 8) |
        $bytes[3]
      );
      $output .= "condjump " . (
        (($bytes[0] & 0x0f) << 4) |
        (($bytes[1] & 0xf0) >> 4)
      ) . ' L_' . sprintf("%.6d", $offset);
    } else {
      die "Unknown opcode $opcode; $output.";
    }
    $output .= "\n";
    ++$label;
  }
}

sub absorb_binary
{
  my $path = shift; die "$path not found" if (! -f $path);
  my $result = '';
  die "Error $@ opening $path" if (!open(FILE, '<', $path));
  binmode FILE;
  my $buf;
  while (1) {
    my $n = sysread(FILE, $buf, 1024);
    if (!$n) {
      close FILE;
      return $result;
    }
    $result .= $buf;
  }
}

1;
