#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

#define SLOT_TOP 0
#define SLOT_S 1
#define SLOT_MULTILINECOMMENT 2
#define SLOT_COMMENT 3
#define SLOT_INSTRUCTIONS 4
#define SLOT_INSTRUCTION 5
#define SLOT_RULEINSTR 6
#define SLOT_END 7
#define SLOT_BACKCOMMITINSTR 8
#define SLOT_CALLINSTR 9
#define SLOT_CATCHINSTR 10
#define SLOT_CLOSECAPTUREINSTR 11
#define SLOT_COMMITINSTR 12
#define SLOT_ENDINSTR 13
#define SLOT_FAILINSTR 14
#define SLOT_FAILTWICEINSTR 15
#define SLOT_OPENCAPTUREINSTR 16
#define SLOT_PARTIALCOMMITINSTR 17
#define SLOT_RETINSTR 18
#define SLOT_RANGEINSTR 19
#define SLOT_VARINSTR 20
#define SLOT_COUNTERINSTR 21
#define SLOT_CONDJUMPINSTR 22
#define SLOT_LABELDEF 23
#define SLOT_HEXBYTE 24
#define SLOT_LABEL 25
#define SLOT_CODE 26
#define SLOT_SLOT 27
#define SLOT_REGISTER 28
#define SLOT_TYPE 29
#define SLOT_UNSIGNED 30
#define SLOT_COLON 31

#endif
