#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

#define SLOT_TOP 0
#define SLOT_S 1
#define SLOT_MULTILINECOMMENT 2
#define SLOT_COMMENT 3
#define SLOT_INSTRUCTIONS 4
#define SLOT_INSTRUCTION 5
#define SLOT_RULEINSTR 6
#define SLOT_END 7
#define SLOT_BACKCOMMITINSTR 8
#define SLOT_CALLINSTR 9
#define SLOT_CATCHINSTR 10
#define SLOT_CLOSECAPTUREINSTR 11
#define SLOT_COMMITINSTR 12
#define SLOT_ENDINSTR 13
#define SLOT_FAILINSTR 14
#define SLOT_FAILTWICEINSTR 15
#define SLOT_LIMITINSTR 16
#define SLOT_OPENCAPTUREINSTR 17
#define SLOT_PARTIALCOMMITINSTR 18
#define SLOT_RETINSTR 19
#define SLOT_RANGEINSTR 20
#define SLOT_VARINSTR 21
#define SLOT_COUNTERINSTR 22
#define SLOT_CONDJUMPINSTR 23
#define SLOT_LABELDEF 24
#define SLOT_HEXBYTE 25
#define SLOT_LABEL 26
#define SLOT_CODE 27
#define SLOT_SLOT 28
#define SLOT_REGISTER 29
#define SLOT_TYPE 30
#define SLOT_UNSIGNED 31
#define SLOT_BIT 32
#define SLOT_COLON 33

#endif
