#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

#define SLOT_INSTRUCTION 1
#define SLOT_1 INSTRUCTION
#define SLOT_TOP 0
#define SLOT_0 TOP
#define SLOT_any 53
#define SLOT_53 any
#define SLOT_backcommit 44
#define SLOT_44 backcommit
#define SLOT_backcommit_0 45
#define SLOT_45 backcommit_0
#define SLOT_call 51
#define SLOT_51 call
#define SLOT_call_0 52
#define SLOT_52 call_0
#define SLOT_catch 17
#define SLOT_17 catch
#define SLOT_catch_0 18
#define SLOT_18 catch_0
#define SLOT_char 42
#define SLOT_42 char
#define SLOT_char_0 43
#define SLOT_43 char_0
#define SLOT_closecapture 15
#define SLOT_15 closecapture
#define SLOT_closecapture_0 16
#define SLOT_16 closecapture_0
#define SLOT_commit 36
#define SLOT_36 commit
#define SLOT_commit_0 37
#define SLOT_37 commit_0
#define SLOT_condjump 57
#define SLOT_57 condjump
#define SLOT_condjump_0 58
#define SLOT_58 condjump_0
#define SLOT_counter 23
#define SLOT_23 counter
#define SLOT_counter_0 24
#define SLOT_24 counter_0
#define SLOT_end 46
#define SLOT_46 end
#define SLOT_end_0 47
#define SLOT_47 end_0
#define SLOT_endisolate 14
#define SLOT_14 endisolate
#define SLOT_endreplace 33
#define SLOT_33 endreplace
#define SLOT_fail 10
#define SLOT_10 fail
#define SLOT_failtwice 59
#define SLOT_59 failtwice
#define SLOT_intrpcapture 8
#define SLOT_8 intrpcapture
#define SLOT_intrpcapture_0 9
#define SLOT_9 intrpcapture_0
#define SLOT_isolate 27
#define SLOT_27 isolate
#define SLOT_isolate_0 28
#define SLOT_28 isolate_0
#define SLOT_jump 4
#define SLOT_4 jump
#define SLOT_jump_0 5
#define SLOT_5 jump_0
#define SLOT_maskedchar 38
#define SLOT_38 maskedchar
#define SLOT_maskedchar_0 39
#define SLOT_39 maskedchar_0
#define SLOT_noop 56
#define SLOT_56 noop
#define SLOT_opencapture 34
#define SLOT_34 opencapture
#define SLOT_opencapture_0 35
#define SLOT_35 opencapture_0
#define SLOT_partialcommit 29
#define SLOT_29 partialcommit
#define SLOT_partialcommit_0 30
#define SLOT_30 partialcommit_0
#define SLOT_quad 21
#define SLOT_21 quad
#define SLOT_quad_0 22
#define SLOT_22 quad_0
#define SLOT_range 49
#define SLOT_49 range
#define SLOT_range_0 50
#define SLOT_50 range_0
#define SLOT_replace 54
#define SLOT_54 replace
#define SLOT_replace_0 55
#define SLOT_55 replace_0
#define SLOT_ret 13
#define SLOT_13 ret
#define SLOT_set 2
#define SLOT_2 set
#define SLOT_set_0 3
#define SLOT_3 set_0
#define SLOT_skip 25
#define SLOT_25 skip
#define SLOT_skip_0 26
#define SLOT_26 skip_0
#define SLOT_span 31
#define SLOT_31 span
#define SLOT_span_0 32
#define SLOT_32 span_0
#define SLOT_testany 19
#define SLOT_19 testany
#define SLOT_testany_0 20
#define SLOT_20 testany_0
#define SLOT_testchar 11
#define SLOT_11 testchar
#define SLOT_testchar_0 12
#define SLOT_12 testchar_0
#define SLOT_testquad 40
#define SLOT_40 testquad
#define SLOT_testquad_0 41
#define SLOT_41 testquad_0
#define SLOT_testset 6
#define SLOT_6 testset
#define SLOT_testset_0 7
#define SLOT_7 testset_0
#define SLOT_trap 48
#define SLOT_48 trap
#define SLOT_var 60
#define SLOT_60 var
#define SLOT_var_0 61
#define SLOT_61 var_0

#endif
