#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

#define SLOT_instr_any 0
#define SLOT_0 instr_any
#define SLOT_instr_backcommit 1
#define SLOT_1 instr_backcommit
#define SLOT_instr_bitmask 2
#define SLOT_2 instr_bitmask
#define SLOT_instr_call 3
#define SLOT_3 instr_call
#define SLOT_instr_catch 4
#define SLOT_4 instr_catch
#define SLOT_instr_char 5
#define SLOT_5 instr_char
#define SLOT_instr_closecapture 6
#define SLOT_6 instr_closecapture
#define SLOT_instr_commit 7
#define SLOT_7 instr_commit
#define SLOT_instr_condjump 8
#define SLOT_8 instr_condjump
#define SLOT_instr_counter 9
#define SLOT_9 instr_counter
#define SLOT_instr_end 10
#define SLOT_10 instr_end
#define SLOT_instr_endisolate 11
#define SLOT_11 instr_endisolate
#define SLOT_instr_endreplace 12
#define SLOT_12 instr_endreplace
#define SLOT_instr_fail 13
#define SLOT_13 instr_fail
#define SLOT_instr_failtwice 14
#define SLOT_14 instr_failtwice
#define SLOT_instr_intrpcapture 15
#define SLOT_15 instr_intrpcapture
#define SLOT_instr_isolate 16
#define SLOT_16 instr_isolate
#define SLOT_instr_jump 17
#define SLOT_17 instr_jump
#define SLOT_instr_noop 18
#define SLOT_18 instr_noop
#define SLOT_instr_opencapture 19
#define SLOT_19 instr_opencapture
#define SLOT_instr_partialcommit 20
#define SLOT_20 instr_partialcommit
#define SLOT_instr_quad 21
#define SLOT_21 instr_quad
#define SLOT_instr_range 22
#define SLOT_22 instr_range
#define SLOT_instr_replace 23
#define SLOT_23 instr_replace
#define SLOT_instr_ret 24
#define SLOT_24 instr_ret
#define SLOT_instr_set 25
#define SLOT_25 instr_set
#define SLOT_instr_skip 26
#define SLOT_26 instr_skip
#define SLOT_instr_span 27
#define SLOT_27 instr_span
#define SLOT_instr_testany 28
#define SLOT_28 instr_testany
#define SLOT_instr_testchar 29
#define SLOT_29 instr_testchar
#define SLOT_instr_testquad 30
#define SLOT_30 instr_testquad
#define SLOT_instr_testset 31
#define SLOT_31 instr_testset
#define SLOT_instr_trap 32
#define SLOT_32 instr_trap
#define SLOT_instr_var 33
#define SLOT_33 instr_var

#endif
