#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

#define SLOT_INSTRUCTION 1
#define SLOT_1 INSTRUCTION
#define SLOT_TOP 0
#define SLOT_0 TOP
#define SLOT_any 2
#define SLOT_2 any
#define SLOT_backcommit 3
#define SLOT_3 backcommit
#define SLOT_backcommit_0 4
#define SLOT_4 backcommit_0
#define SLOT_call 5
#define SLOT_5 call
#define SLOT_call_0 6
#define SLOT_6 call_0
#define SLOT_catch 7
#define SLOT_7 catch
#define SLOT_catch_0 8
#define SLOT_8 catch_0
#define SLOT_char 9
#define SLOT_9 char
#define SLOT_char_0 10
#define SLOT_10 char_0
#define SLOT_closecapture 11
#define SLOT_11 closecapture
#define SLOT_closecapture_0 12
#define SLOT_12 closecapture_0
#define SLOT_commit 13
#define SLOT_13 commit
#define SLOT_commit_0 14
#define SLOT_14 commit_0
#define SLOT_condjump 15
#define SLOT_15 condjump
#define SLOT_condjump_0 16
#define SLOT_16 condjump_0
#define SLOT_counter 17
#define SLOT_17 counter
#define SLOT_counter_0 18
#define SLOT_18 counter_0
#define SLOT_end 19
#define SLOT_19 end
#define SLOT_end_0 20
#define SLOT_20 end_0
#define SLOT_endisolate 21
#define SLOT_21 endisolate
#define SLOT_endreplace 22
#define SLOT_22 endreplace
#define SLOT_fail 23
#define SLOT_23 fail
#define SLOT_failtwice 24
#define SLOT_24 failtwice
#define SLOT_intrpcapture 25
#define SLOT_25 intrpcapture
#define SLOT_intrpcapture_0 26
#define SLOT_26 intrpcapture_0
#define SLOT_isolate 27
#define SLOT_27 isolate
#define SLOT_isolate_0 28
#define SLOT_28 isolate_0
#define SLOT_jump 29
#define SLOT_29 jump
#define SLOT_jump_0 30
#define SLOT_30 jump_0
#define SLOT_maskedchar 31
#define SLOT_31 maskedchar
#define SLOT_maskedchar_0 32
#define SLOT_32 maskedchar_0
#define SLOT_noop 33
#define SLOT_33 noop
#define SLOT_opencapture 34
#define SLOT_34 opencapture
#define SLOT_opencapture_0 35
#define SLOT_35 opencapture_0
#define SLOT_partialcommit 36
#define SLOT_36 partialcommit
#define SLOT_partialcommit_0 37
#define SLOT_37 partialcommit_0
#define SLOT_quad 38
#define SLOT_38 quad
#define SLOT_quad_0 39
#define SLOT_39 quad_0
#define SLOT_range 40
#define SLOT_40 range
#define SLOT_range_0 41
#define SLOT_41 range_0
#define SLOT_replace 42
#define SLOT_42 replace
#define SLOT_replace_0 43
#define SLOT_43 replace_0
#define SLOT_ret 44
#define SLOT_44 ret
#define SLOT_set 45
#define SLOT_45 set
#define SLOT_set_0 46
#define SLOT_46 set_0
#define SLOT_skip 47
#define SLOT_47 skip
#define SLOT_skip_0 48
#define SLOT_48 skip_0
#define SLOT_span 49
#define SLOT_49 span
#define SLOT_span_0 50
#define SLOT_50 span_0
#define SLOT_testany 51
#define SLOT_51 testany
#define SLOT_testany_0 52
#define SLOT_52 testany_0
#define SLOT_testchar 53
#define SLOT_53 testchar
#define SLOT_testchar_0 54
#define SLOT_54 testchar_0
#define SLOT_testquad 55
#define SLOT_55 testquad
#define SLOT_testquad_0 56
#define SLOT_56 testquad_0
#define SLOT_testset 57
#define SLOT_57 testset
#define SLOT_testset_0 58
#define SLOT_58 testset_0
#define SLOT_trap 59
#define SLOT_59 trap
#define SLOT_var 60
#define SLOT_60 var
#define SLOT_var_0 61
#define SLOT_61 var_0

#endif
