#!/usr/bin/perl

use strict;

my $inputfile = '-';
my $outputfile = '-';
my $ignore_unknown = 0;

while (scalar(@ARGV)) {
  my $arg = shift @ARGV;
  if ($arg =~ s/^-//) {
    if ($arg eq 'i' || $arg eq '-inputfile') {
      $inputfile = shift @ARGV;
    } elsif ($arg eq 'o' || $arg eq '-outputfile') {
      $outputfile = shift @ARGV;
    } elsif ($arg eq '-ignore-unknown') {
      $ignore_unknown = 1;
    }
  } else {
    die "Unknown argument $arg";
  }
}

my $input;
if ($inputfile eq '-') {
  $input = join('', <STDIN>);
} else {
  $input = `cat $inputfile`;
}

my @tokens;
my %labels;
my $offset = 0;
while (length($input)) {
  while ($input =~ s/^\s+// || $input =~ s/^--.*?\n//) { }
  last if (!length($input));
  if ($input =~ s/^end(\s+([0-9]+))?//) {
    push @tokens, { type => 'end' };
    $offset += 4;
  } elsif ($input =~ s/^range\s+//) {
    my ($truerange, $nbits, $bitmask, $from, $until) = (1, 8, 0xff, 0, 0);
    if ($input =~ s/^(true|false)\s+([0-9]+)\s+//) {
      $truerange = ($1 eq 'true') ? 1 : 0;
      $nbits = $2;
    }
    if ($input =~ s/^([a-fA-F0-9]{2})\s+//) {
      $from = hex($1);
      $until = $from;
      if ($input =~ s/^([a-fA-F0-9]{2})\s+//) {
        $until = hex($1);
        if ($input =~ s/^([a-fA-F0-9]{2})\s+//) {
          $bitmask = hex($1);
        }
      }
    }
    die "Range contains LPEG unsupportable bitmask" if ($bitmask != 0xff);
    die "Range contains LPEG unsupportable nbits" if ($nbits != 8);
    if ($truerange) {
      if ($from == 0 && $until == 255) {
        push @tokens, { type => 'any' };
        $offset += 4;
      } elsif ($from == $until) {
        push @tokens, { type => 'char', char => $from };
        $offset += 4;
      } else {
        push @tokens, { type => 'set', from => $from, until => $until };
        $offset += 36;
      }
    } elsif ($from == $until) {
      push @tokens, { type => 'char', char => $from };
      $offset += 4;
    } else {
##.. either or from or until
    }
  } elsif ($input =~ s/^(limit|(open|close)capture|counter|condjump)\s+//) {
    if (!$ignore_unknown) {
      die "Assembly '$1' instruction, which can't be translated to LPEG";
    } else {
      $input =~ s/^.*?\n//;
    }
  } elsif ($input =~ s/^call\s+([a-zA-Z0-9_-]+)//) {
    push @tokens, { type => 'call', label => $1 };
    $offset += 8;
  } elsif ($input =~ s/^ret\s+//) {
    push @tokens, { type => 'ret' };
    $offset += 4;
  } elsif ($input =~ s/^(catch|choice)\s+([a-zA-Z0-9_-]+)//) {
    push @tokens, { type => 'choice', label => $2 };
    $offset += 8;
  } elsif ($input =~ s/^commit\s+([a-zA-Z0-9_-]+)//) {
    push @tokens, { type => 'commit', label => $1 };
    $offset += 8;
  } elsif ($input =~ s/^backcommit\s+([a-zA-Z0-9_-]+)//) {
    push @tokens, { type => 'backcommit', label => $1 };
    $offset += 8;
  } elsif ($input =~ s/^partialcommit\s+([a-zA-Z0-9_-]+)//) {
    push @tokens, { type => 'partialcommit', label => $1 };
    $offset += 8;
  } elsif ($input =~ s/^failtwice\s+//) {
    push @tokens, { type => 'failtwice' };
    $offset += 4;
  } elsif ($input =~ s/^fail\s+//) {
    push @tokens, { type => 'fail' };
    $offset += 4;
  } elsif ($input =~ s/^([0-9a-zA-Z_-]+)\s*://) {
    $labels{$1} = $offset;
  } else {
    die "Unknown token at '$input'";
  }
}

my $instr = {
  end => 9,
  any => 0,
  set => 2,
  char => 1,
  call => 12,
  ret => 8,
  catch => 10,
  choice => 10,
  commit => 14,
  backcommit => 16,
  partialcommit => 15,
  failtwice => 17,
  fail => 18,
};

sub quad
{
  my ($c0, $c1, $c2, $c3) = @_;
  return chr($c0) . chr($c1) . chr($c2) . chr($c3);
}

sub pack_sig_low_32
{
  my $n = shift;
  my $neg = 0;
  if ($n < 0) {
    $neg = 1;
    $n = -$n;
  }
  my $res =
    chr($n & 0xff) . chr(($n >> 8) & 0xff) . chr(($n >> 16) & 0xff) .
    chr((($n >> 24) & 0x7f) | ($neg ? 0x80 : 0x00));
  return $res;
}

my $bytecode = '';
foreach my $token (@tokens) {
  if ($token->{type} =~ /^(end|any|ret|failtwice|fail)$/) {
    $bytecode .= quad($instr->{$token->{type}}, 0, 0, 0);
  } elsif ($token->{type} eq 'set') {
    $bytecode .= quad($instr->{$token->{type}}, 0, 0, 0);
    my $charset = [ (0 x 32) ];
    for (my $i=$token->{from}; $i <= $token->{until}; $i++) {
      $charset->[ int($i/8) ] |= (1<<($i%8));
    }
    for (my $i=0; $i < 32; $i++) {
      $bytecode .= chr($charset->[ $i ]);
    }
  } elsif ($token->{type} eq 'char') {
    $bytecode .= quad($instr->{char}, $token->{char}, 0, 0);
  } elsif ($token->{type} =~ /^(call|catch|choice|(back|partial|)commit)$/) {
    my $reloffset;
    {
      if ($token->{label} eq '__NEXT__') {
        $reloffset = 8;
      } else {
        my $offset = $labels{$token->{label}};
        die "Couldn't find label $token->{label}" if (!defined($offset));
        $reloffset = $offset - length($bytecode);
      }
    }
    $bytecode .=
      quad($instr->{$token->{type}}, 0, 0, 0) .
      pack_sig_low_32($reloffset / 4);
  } else {
    die "Unknown token $token->{type}";
  }
}

if ($outputfile eq '-') {
  syswrite STDOUT, $bytecode;
} else {
  open FILE, "> $outputfile" || die "Could not open output file $outputfile";
  syswrite FILE, $bytecode;
  close FILE;
}

1;
