/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _GPEG_FUNCTIONS_FUNCTIONS_H_
#define _GPEG_FUNCTIONS_FUNCTIONS_H_

/* declared in ./gpeg_capturelist.c */
extern
void gpeg_capturelist_debug
  (gpeg_capturelist_t* list);

/* declared in ./gpeg_capturelist.c */
extern
void gpeg_capture_debug
  (gpeg_capture_t* capture);

/* declared in ./gpeg_capturelist.c */
extern
void gpeg_capturelist_remove
  (gpeg_capturelist_t* list, unsigned type);

/* declared in ./gpeg_compile.c */
extern
int gpeg_compile
  (char* grammar, gpege_t* engine)
  __attribute__ ((warn_unused_result));

/* declared in ./gpeg_opcode2string.c */
extern
char* gpeg_opcode2string
  (unsigned opcode)
  __attribute__ ((warn_unused_result));

/* declared in ./gpeg_run.c */
extern
int gpeg_run
  (gpege_t* engine, vec_t* input, int* resultcode, gpeg_capturelist_t* result)
  __attribute__ ((warn_unused_result));



#endif