/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _GPEGC_FUNCTIONS_H__FUNCTIONS_H_
#define _GPEGC_FUNCTIONS_H__FUNCTIONS_H_

#include <gpeg/lib/gpeg/gpeg_defines.h>
#include <gpeg/lib/compiler/gpegc_types.h>

extern
GPEG_ERR_T gpegc_compile
  (gpegc_compiler_t c[ static 1 ])
  __attribute__ ((warn_unused_result));

#endif
