/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _GPEGC_FUNCTIONS_H__FUNCTIONS_H_
#define _GPEGC_FUNCTIONS_H__FUNCTIONS_H_

#include <gpeg/private/util/vec_t.h>

#define GPEG_COMPILE_FLAG_RULECAPTURE   (1<<0)

extern
GPEG_ERR_T gpegc_compile
  (vec_t* input, vec_t* output, vec_t* error, unsigned flags)
  __attribute__ ((warn_unused_result));

#endif
